# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
branches:
  only:
    - master
os:
  - linux
julia:
  - 1
  - nightly
notifications:
  email: false
jobs:
   fast_finish: true
   allow_failures:
     - julia: nightly
   include:
     - stage: Documentation
       julia: 1
       script: |
         julia --project=docs -e '
           using Pkg
           Pkg.develop(PackageSpec(path=pwd()))
           Pkg.instantiate()
           using Documenter: doctest
           using BioMASS
           doctest(BioMASS)
           include("docs/make.jl")'
       after_success: skip
