name = "BioMASS"
uuid = "324734c7-f323-4536-9335-775d9be9d101"
authors = ["Hiroaki Imoto <himoto@protein.osaka-u.ac.jp>"]
version = "0.1.0"

[compat]
julia = "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
